### ISSUE TITLE
Physics bug

### ISSUE THREAD

**Issue by leitcama** [JacobKrol/Planar-Disk-Packing#2]
@JacobKrol I think the problem seems to be that the circles never settle by themselves, they are just stopping the movement after a predetermined amount of time (Settletime). This leaves the last position of the circles unresolved and potentially intersecting (which is seen in the Arrays Input.html)

**Comment by leitcama** [comment]
Also, when you try creating 400 circles, the program takes forever, the algorithm is 'blowing up' at large numbers.

**Comment by jacobkrol** [comment]
Your first comment makes sense. In js, the circles will quickly correct themselves, but here, we are trying to predict how long this process will take by predetermining a "circletime" and "settletime." We may need to rethink that strategy. Feel free to make some progress there to debug it so the circles end up outside of each other. As far as your second note is concerned, that will be up to Rohit to look into.
